CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

CREATE TABLE "Checkouts" (
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "CheckoutDate" timestamp without time zone NOT NULL,
    "DueDate" timestamp without time zone NOT NULL,
    "ReturnDate" timestamp without time zone NOT NULL,
    "CheckoutStatus" integer NOT NULL,
    "ApprovalStatus" integer NOT NULL,
    CONSTRAINT "PK_Checkouts" PRIMARY KEY ("Id")
);

CREATE TABLE "ItemGroups" (
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "Moniker" text NULL,
    "Make" text NULL,
    "Model" text NULL,
    "Description" text NULL,
    "Category" text NULL,
    "Department" text NULL,
    CONSTRAINT "PK_ItemGroups" PRIMARY KEY ("Id")
);

CREATE TABLE "Items" (
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "SerialNumber" text NULL,
    "Availability" integer NOT NULL,
    "OffsiteEligable" boolean NOT NULL,
    "DateAcquired" timestamp without time zone NOT NULL,
    "LastInspected" timestamp without time zone NOT NULL,
    "Condition" integer NOT NULL,
    "Notes" text NULL,
    "CheckoutId" integer NULL,
    "ItemGroupId" integer NULL,
    CONSTRAINT "PK_Items" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Items_Checkouts_CheckoutId" FOREIGN KEY ("CheckoutId") REFERENCES "Checkouts" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_Items_ItemGroups_ItemGroupId" FOREIGN KEY ("ItemGroupId") REFERENCES "ItemGroups" ("Id") ON DELETE RESTRICT
);

CREATE INDEX "IX_Items_CheckoutId" ON "Items" ("CheckoutId");

CREATE INDEX "IX_Items_ItemGroupId" ON "Items" ("ItemGroupId");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20200704212055_InitialDbMigration', '3.1.7');

ALTER TABLE "Checkouts" ALTER COLUMN "CheckoutStatus" TYPE integer;
ALTER TABLE "Checkouts" ALTER COLUMN "CheckoutStatus" DROP NOT NULL;
ALTER TABLE "Checkouts" ALTER COLUMN "CheckoutStatus" DROP DEFAULT;

ALTER TABLE "Checkouts" ALTER COLUMN "CheckoutDate" TYPE timestamp without time zone;
ALTER TABLE "Checkouts" ALTER COLUMN "CheckoutDate" SET NOT NULL;
ALTER TABLE "Checkouts" ALTER COLUMN "CheckoutDate" SET DEFAULT TIMESTAMP '2020-09-01 20:44:05.1298';

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20200902034405_DefaultCheckoutDateToNow', '3.1.7');

ALTER TABLE "Checkouts" ALTER COLUMN "CheckoutStatus" TYPE integer;
ALTER TABLE "Checkouts" ALTER COLUMN "CheckoutStatus" DROP NOT NULL;
ALTER TABLE "Checkouts" ALTER COLUMN "CheckoutStatus" SET DEFAULT 3;

ALTER TABLE "Checkouts" ALTER COLUMN "CheckoutDate" TYPE timestamp without time zone;
ALTER TABLE "Checkouts" ALTER COLUMN "CheckoutDate" SET NOT NULL;
ALTER TABLE "Checkouts" ALTER COLUMN "CheckoutDate" SET DEFAULT (NOW());

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20200902204736_DefaultCheckoutDate2', '3.1.7');

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20200902211623_CheckoutDateDefaultVal3', '3.1.7');

ALTER TABLE "Checkouts" ALTER COLUMN "ReturnDate" TYPE timestamp without time zone;
ALTER TABLE "Checkouts" ALTER COLUMN "ReturnDate" DROP NOT NULL;
ALTER TABLE "Checkouts" ALTER COLUMN "ReturnDate" DROP DEFAULT;

ALTER TABLE "Checkouts" ALTER COLUMN "CheckoutDate" TYPE timestamp without time zone;
ALTER TABLE "Checkouts" ALTER COLUMN "CheckoutDate" DROP NOT NULL;
ALTER TABLE "Checkouts" ALTER COLUMN "CheckoutDate" SET DEFAULT (NOW());

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20200902213754_CheckoutDateDefaultVal4', '3.1.7');

